import { Business, User, Engineer, Customer, ServiceItem, Booking, Invoice, ChatMessage, NotificationItem } from '@/types';

export const mockBusiness: Business = {
  id: 'biz_01',
  name: 'WEIC Smart Trade Solutions UK',
  slug: 'weic-trade-uk',
  logo: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=250&auto=format&fit=crop',
  primaryColor: '#0284c7', // Sky Blue
  accentColor: '#f59e0b', // Amber Gold
  phone: '+44 20 7946 0912',
  email: 'contact@weic.co.uk',
  address: '102 Baker Street, Marylebone',
  city: 'London',
  postcode: 'W1U 68A',
  currency: '£',
  vatRate: 20,
  hourlyRate: 65.0,
  emergencyMultiplier: 1.5,
  weekendMultiplier: 1.25,
  callOutFee: 45.0,
  googlePlaceId: 'ChIJdd4hrwug2EcRmSrV3Vo6llI',
  rating: 4.9,
  reviewCount: 342,
};

export const mockEngineers: Engineer[] = [
  {
    id: 'eng_101',
    businessId: 'biz_01',
    role: 'engineer',
    name: 'David Gascoigne',
    email: 'david.g@weic.co.uk',
    phone: '+44 7700 900123',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop',
    skills: ['Gas Safe Certified', 'Boiler Installation', 'Heat Pump Repair', 'Central Heating'],
    certifications: ['Gas Safe #592810', 'NVQ Level 3 Plumbing', 'City & Guilds 6035'],
    vehicleRegistration: 'BD68 WXY (Ford Transit Custom)',
    isAvailable: true,
    currentLat: 51.5155,
    currentLng: -0.1310,
    rating: 4.95,
    completedJobsCount: 148,
    activeJobId: 'bk_2001',
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'eng_102',
    businessId: 'biz_01',
    role: 'engineer',
    name: 'James Wright (Part P Electrician)',
    email: 'james.w@weic.co.uk',
    phone: '+44 7700 900456',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    skills: ['Part P Registered', 'Consumer Unit Upgrade', 'EV Charger Install', 'Rewiring'],
    certifications: ['NICEIC Approved Contractor', '18th Edition Wiring Regulations'],
    vehicleRegistration: 'LN21 KJL (Vauxhall Vivaro Electric)',
    isAvailable: true,
    currentLat: 51.5074,
    currentLng: -0.1278,
    rating: 4.88,
    completedJobsCount: 210,
    createdAt: '2023-11-10T09:00:00Z',
  },
  {
    id: 'eng_103',
    businessId: 'biz_01',
    role: 'engineer',
    name: 'Sarah O\'Connor',
    email: 'sarah.oc@weic.co.uk',
    phone: '+44 7700 900789',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
    skills: ['Emergency Locksmith', 'Smart Lock Setup', 'uPVC Door Mechanisms', 'Security Audits'],
    certifications: ['MLA Master Locksmiths Association', 'DBS Checked'],
    vehicleRegistration: 'EF72 NMP (Volkswagen Transporter)',
    isAvailable: true,
    currentLat: 51.5200,
    currentLng: -0.1400,
    rating: 5.0,
    completedJobsCount: 95,
    createdAt: '2024-03-01T09:00:00Z',
  },
  {
    id: 'eng_104',
    businessId: 'biz_01',
    role: 'engineer',
    name: 'Marcus Bell',
    email: 'marcus.b@weic.co.uk',
    phone: '+44 7700 900321',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    skills: ['HVAC Servicing', 'Air Conditioning Unit', 'Ventilation Systems', 'Refrigeration'],
    certifications: ['F-Gas Certified', 'Refcom Registered'],
    vehicleRegistration: 'GX69 HJK (Peugeot Partner)',
    isAvailable: false,
    currentLat: 51.4980,
    currentLng: -0.1300,
    rating: 4.79,
    completedJobsCount: 164,
    createdAt: '2023-08-20T09:00:00Z',
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cust_301',
    businessId: 'biz_01',
    role: 'customer',
    name: 'Eleanor Vance',
    email: 'eleanor.vance@example.co.uk',
    phone: '+44 7890 123456',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop',
    address: '42 Kensington High Street',
    postcode: 'W8 4PT',
    totalBookings: 3,
    createdAt: '2024-02-10T10:00:00Z',
  },
  {
    id: 'cust_302',
    businessId: 'biz_01',
    role: 'customer',
    name: 'Robert Sterling',
    email: 'r.sterling@example.co.uk',
    phone: '+44 7890 654321',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
    address: '15 Piccadilly Circus',
    postcode: 'W1J 0DA',
    totalBookings: 1,
    createdAt: '2024-04-12T11:30:00Z',
  },
];

export const mockServices: ServiceItem[] = [
  {
    id: 'srv_01',
    businessId: 'biz_01',
    category: 'plumbing',
    title: 'Emergency Boiler Repair & Diagnostics',
    description: 'Rapid response for leaking boilers, loss of pressure, no hot water or heating.',
    basePrice: 95.0,
    estimatedDurationMins: 90,
    isEmergencyAvailable: true,
    requiredSkills: ['Gas Safe Certified', 'Boiler Installation'],
  },
  {
    id: 'srv_02',
    businessId: 'biz_01',
    category: 'electrical',
    title: 'Consumer Unit / Fuse Box Replacement',
    description: '18th Edition RCD/RCBO surge protection consumer unit upgrade with EICR certification.',
    basePrice: 380.0,
    estimatedDurationMins: 240,
    isEmergencyAvailable: false,
    requiredSkills: ['Part P Registered'],
  },
  {
    id: 'srv_03',
    businessId: 'biz_01',
    category: 'locksmith',
    title: 'Emergency Lock Out & Cylinders Upgrade',
    description: '24/7 non-destructive entry, Ultion high security 3* anti-snap cylinder fitting.',
    basePrice: 85.0,
    estimatedDurationMins: 45,
    isEmergencyAvailable: true,
    requiredSkills: ['Emergency Locksmith'],
  },
  {
    id: 'srv_04',
    businessId: 'biz_01',
    category: 'hvac',
    title: 'Commercial/Residential AC Maintenance',
    description: 'Filter cleaning, refrigerant pressure check, leak test, anti-bacterial flush.',
    basePrice: 120.0,
    estimatedDurationMins: 120,
    isEmergencyAvailable: false,
    requiredSkills: ['HVAC Servicing'],
  },
  {
    id: 'srv_05',
    businessId: 'biz_01',
    category: 'plumbing',
    title: 'Annual Gas Safety Certificate (CP12)',
    description: 'Landlord gas inspection for up to 3 appliances with instant digital certificate.',
    basePrice: 75.0,
    estimatedDurationMins: 60,
    isEmergencyAvailable: false,
    requiredSkills: ['Gas Safe Certified'],
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'bk_2001',
    bookingRef: 'WEIC-94821',
    businessId: 'biz_01',
    customerId: 'cust_301',
    customerName: 'Eleanor Vance',
    customerPhone: '+44 7890 123456',
    customerEmail: 'eleanor.vance@example.co.uk',
    serviceId: 'srv_01',
    serviceTitle: 'Emergency Boiler Repair & Diagnostics',
    category: 'plumbing',
    status: 'en_route',
    scheduledDate: '2026-08-01',
    scheduledTime: '08:30 AM',
    address: '42 Kensington High Street, London',
    postcode: 'W8 4PT',
    lat: 51.5010,
    lng: -0.1915,
    issueDescription: 'Worcester Bosch boiler displaying Error EA (no spark). Radiators freezing cold.',
    photos: [
      'https://images.unsplash.com/photo-1585338107529-13afc5f02586?q=80&w=400&auto=format&fit=crop'
    ],
    isEmergency: true,
    assignedEngineerId: 'eng_101',
    assignedEngineerName: 'David Gascoigne',
    assignedEngineerPhone: '+44 7700 900123',
    assignedEngineerAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop',
    assignedEngineerVehicle: 'BD68 WXY (Ford Transit)',
    engineerLat: 51.5085,
    engineerLng: -0.1650,
    etaMins: 12,
    pricing: {
      basePrice: 95.0,
      labourCost: 65.0,
      distanceFee: 15.0,
      emergencyFee: 47.5,
      weekendFee: 0,
      materialsCost: 35.0,
      discount: 10.0,
      subtotal: 247.5,
      vatAmount: 49.5,
      total: 297.0,
    },
    createdAt: '2026-08-01T07:15:00Z',
  },
  {
    id: 'bk_2002',
    bookingRef: 'WEIC-94822',
    businessId: 'biz_01',
    customerId: 'cust_302',
    customerName: 'Robert Sterling',
    customerPhone: '+44 7890 654321',
    customerEmail: 'r.sterling@example.co.uk',
    serviceId: 'srv_03',
    serviceTitle: 'Emergency Lock Out & Cylinders Upgrade',
    category: 'locksmith',
    status: 'assigned',
    scheduledDate: '2026-08-01',
    scheduledTime: '10:00 AM',
    address: '15 Piccadilly Circus, London',
    postcode: 'W1J 0DA',
    lat: 51.5100,
    lng: -0.1340,
    issueDescription: 'Front door Yale lock snapped key inside. Urgent entry needed.',
    photos: [],
    isEmergency: true,
    assignedEngineerId: 'eng_103',
    assignedEngineerName: 'Sarah O\'Connor',
    assignedEngineerPhone: '+44 7700 900789',
    assignedEngineerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
    assignedEngineerVehicle: 'EF72 NMP (VW Transporter)',
    engineerLat: 51.5200,
    engineerLng: -0.1400,
    etaMins: 25,
    pricing: {
      basePrice: 85.0,
      labourCost: 65.0,
      distanceFee: 10.0,
      emergencyFee: 42.5,
      weekendFee: 0,
      materialsCost: 45.0,
      discount: 0,
      subtotal: 247.5,
      vatAmount: 49.5,
      total: 297.0,
    },
    createdAt: '2026-08-01T07:20:00Z',
  },
  {
    id: 'bk_2003',
    bookingRef: 'WEIC-94809',
    businessId: 'biz_01',
    customerId: 'cust_301',
    customerName: 'Eleanor Vance',
    customerPhone: '+44 7890 123456',
    customerEmail: 'eleanor.vance@example.co.uk',
    serviceId: 'srv_02',
    serviceTitle: 'Consumer Unit / Fuse Box Replacement',
    category: 'electrical',
    status: 'completed',
    scheduledDate: '2026-07-28',
    scheduledTime: '02:00 PM',
    address: '42 Kensington High Street, London',
    postcode: 'W8 4PT',
    lat: 51.5010,
    lng: -0.1915,
    issueDescription: 'Old rewirable fuse box replaced with dual RCD consumer board.',
    photos: [],
    isEmergency: false,
    assignedEngineerId: 'eng_102',
    assignedEngineerName: 'James Wright',
    assignedEngineerPhone: '+44 7700 900456',
    assignedEngineerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    pricing: {
      basePrice: 380.0,
      labourCost: 130.0,
      distanceFee: 0,
      emergencyFee: 0,
      weekendFee: 0,
      materialsCost: 110.0,
      discount: 20.0,
      subtotal: 600.0,
      vatAmount: 120.0,
      total: 720.0,
    },
    createdAt: '2026-07-25T14:00:00Z',
    completedAt: '2026-07-28T17:30:00Z',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv_7001',
    invoiceNumber: 'INV-2026-WEIC-081',
    bookingId: 'bk_2003',
    businessId: 'biz_01',
    customerId: 'cust_301',
    customerName: 'Eleanor Vance',
    customerEmail: 'eleanor.vance@example.co.uk',
    customerAddress: '42 Kensington High Street, W8 4PT, London',
    issueDate: '2026-07-28',
    dueDate: '2026-08-11',
    items: [
      { description: '18th Edition Consumer Board Replacement Labour', quantity: 1, unitPrice: 380.0, amount: 380.0 },
      { description: 'Hager 10-Way Dual RCD Enclosure + MCBs', quantity: 1, unitPrice: 110.0, amount: 110.0 },
      { description: 'Electrical Installation Certificate (EICR Logged)', quantity: 1, unitPrice: 110.0, amount: 110.0 },
    ],
    subtotal: 600.0,
    vatAmount: 120.0,
    totalAmount: 720.0,
    status: 'paid',
    stripePaymentId: 'ch_3N8zX2Lkd901xLK',
    paidAt: '2026-07-28T17:45:00Z',
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg_01',
    bookingId: 'bk_2001',
    senderId: 'eng_101',
    senderName: 'David Gascoigne (WEIC Engineer)',
    senderRole: 'engineer',
    content: 'Good morning Eleanor! I have picked up the replacement Worcester pressure sensor valve from WEIC warehouse and I am en route now via A4. ETA 12 mins.',
    timestamp: '08:18 AM',
    read: true,
  },
  {
    id: 'msg_02',
    bookingId: 'bk_2001',
    senderId: 'cust_301',
    senderName: 'Eleanor Vance (Customer)',
    senderRole: 'customer',
    content: 'Thank you David! The front gate code is #4821. Parking space available right in front.',
    timestamp: '08:20 AM',
    read: true,
  },
  {
    id: 'msg_03',
    bookingId: 'bk_2001',
    senderId: 'eng_101',
    senderName: 'David Gascoigne (WEIC Engineer)',
    senderRole: 'engineer',
    content: 'Brilliant, noted! See you shortly.',
    timestamp: '08:21 AM',
    read: true,
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif_01',
    userId: 'cust_301',
    title: 'WEIC Engineer En Route',
    message: 'David Gascoigne is en route to your property in Ford Transit BD68 WXY.',
    type: 'dispatch',
    read: false,
    timestamp: '10 mins ago',
  },
  {
    id: 'notif_02',
    userId: 'biz_owner',
    title: 'New Google Business Booking',
    message: 'Booking #WEIC-94822 received via Google Business Profile for WEIC Emergency Locksmith.',
    type: 'booking',
    read: true,
    timestamp: '25 mins ago',
  },
];
